# Generated by Django 5.1.5 on 2025-02-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('marcado', 'Marcado'), ('realizado', 'Realizado'), ('pago', 'Pago'), ('cancelado', 'Caancelado')], default='marcado', max_length=10),
        ),
    ]
